### PR TITLE
Had the chance to make 3 Display compatible to the Library, HINKE0154A35, HINKE029A14 and HINKE042A11

### PR DESCRIPTION
**Pull request by atc1441**

### CODE REVIEW

**Comment by atc1441** [comment]
Why was it closed?

**Comment by ZinggJM** [comment]
1. I don't need to justify, its my decision.
2. I didn't like it.
3. I don't merge pull requests anymore.
4. I don't add support for e-paper displays I don't have.

I will not add any comments about your pictures and your code here.

**Comment by mcer12** [comment]
@atc1441 thanks for posting the issue, without this hint I would have had a dead display! It lead me to your pull request and youtube channel. Nice work and thank you for the effort :+1:
@ZinggJM wow, you must be fun at parties.

**Comment by IIAIronWolf** [comment]
@atc1441 just make your own fork

**Pull request closed without merging**
