### PR TITLE
Added support for GxGDEW042Z15

### PR DESCRIPTION
**Pull request by jknipper**
Added support for GxGDEW042Z15, eg. Waveshare 4.2" black/white/red e-paper module.

### CODE REVIEW

**Comment by sidoh** [comment]
Hi @jknipper, is this working for you?  My screen is unresponsive when running with this code.  The waveshare example code does work, so pretty confident it's not a hardware issue.

**Comment by G6EJD** [comment]
I’m using it and it’s OK, make sure you place all of the GxEPD includes and definitions as early as possible and I presume there are no compiler messages, also are you using an ESP32?

**Comment by sidoh** [comment]
Using an ESP8266.

Right, no compiler errors or warnings, and nothing in serial logs.  init completes successfully.  I checked that I had the pin mappings right a bunch of times.

This is the sketch I'm using in case that's helpful:

https://gist.github.com/sidoh/0cb230508da8a05666795910e6bb589f

The same sketch worked with a 1.54" RGBW display (obviously with changes to the includes).

**Comment by G6EJD** [comment]
My eyes are drawn to the include bitmap test because the memory usage is high and marginal on the ESP8266 you need about 30% free to enable the bit maps to be built noting the 400x300 rendering is larger than the 200x200 of the 1.54 unit.

Does it work in text only mode?

I’m not using the 8266 an ESP32

**Comment by sidoh** [comment]
Hm, fair point, but I would expect crashes or other bizarre behaviors if the stack ran into the heap, but not seeing that.  It just happily putters along, but the screen doesn't do anything.  Also checked free heap at the end of `setup` with `ESP.getFreeHeap()` and it reports 15 KB of free RAM.  I would think that should be plenty to prevent memory trouble.

Seeing the same thing when commenting out the include bitmap.  Is that what you mean by text mode.  Sorry if I'm missing something obvious -- new to this library :)

I have an ESP32 I could try with, but would prefer to use an ESP8266 if possible.

Will try poking around a bit on my own.  It's good just to know it's working for others! :)

EDIT - forgot to mention the most important thing: thank you for your help!

**Comment by G6EJD** [comment]
The library author states the need for a minimum of 22K of free ram to enable a bit image to be constructed before transfer to the display, it looks like your well below that requirement. When I meant text mode I was wondering if a simple “hello world” display example works or not?

**Comment by sidoh** [comment]
Thank you again for your help :)

I was referring to there being 15 KB of free RAM _after_ initialization, which I assume includes the construction of frame buffers and whatever else the library needs.  Meant to offer the fact that there's still a fair amount of free memory leftover (ESP8266 only has 64KB) as evidence that there's probably enough memory.

`display.init()` appears to complete successfully.  That method appears to involve polling for the BUSY pin.  There's no timeout in serial logs, but it also doesn't complete instantaneously (takes ~250ms).  I'm assuming this means there's some communication happening between the display and the ESP.

The sketch I pasted is actually an attempt at what amounts to a simple hello world example.  Minus includes and stuff, this is the whole sketch:

```c++
GxIO_Class io(SPI, SS, D2, D1, D4); 
GxEPD_Class display(io); // default selection of D4(=2), D2(=4)

void setup()
{
  Serial.begin(115200);
  Serial.println();
  Serial.println("setup");
  Serial.println(ESP.getFreeHeap());

  display.init();
  display.eraseDisplay(false);
  display.update();

  // display.drawRect(0, 0, 100, 100, GxEPD_BLACK);
  // display.update();
  // display.drawBitmap(BitmapExample2, 0, 0, 200, 200, GxEPD_WHITE);
  // display.update();
  display.setRotation(1);
  display.setFont(&FreeSans18pt7b);
  display.setTextColor(GxEPD_BLACK);
  display.setCursor(0, 20);
  display.println("TEST ");
  display.setTextColor(GxEPD_RED);
  display.println("TEST ");
  display.update();

  Serial.println("setup done");
  Serial.println(ESP.getFreeHeap());
}

void loop() {

}
```

Doesn't do anything even when it's just:

```c++
  display.init();
  display.eraseDisplay(false);
  display.update();
```

Is there something simpler I could try?

**Comment by G6EJD** [comment]
The library does not allocate memory for display rendering at start and builds and consume ram just before display. So you won’t see the dynamic memory use unless you place various diagnostic prints to monitor its use, been there!

I would try one of the other drivers for the 2.7 or 1.54 displays as there is some similarities with the display driver chip, I know the 42 driver works on the 2.9 display albeit the pixel sizes and orientation is wrong. 

It’s a long running ‘battle’ with Waveshare that they don’t or won’t release the waveforms needed to drive their (re-badged) displays, I think we’re all trying to get the displays running and this library author has gone a long way to make that happen but really Waveshare should provide the beasic support, after all what good is a display if it’s not usable!

Your program is as simple as it gets and yet not working, so I wonder how old your display is, either very new or had it for about 2-months the length of time it’s been on the market, something may hav3 changed in the hardware.

**Comment by G6EJD** [comment]
Also worth trying is omitting the fonts as that takes a lot of memory. I think on the ESP8266 you should be getting about 28K free RAM with a minimal programme.

**Comment by sidoh** [comment]
I have the checks in a couple of places.  Roughly the same in all places.  Seems like the frame buffers are allocated within the display class (e.g., `uint8_t _black_buffer[GxGDEW042Z15_BUFFER_SIZE];`).  I'm pretty confident -- perhaps foolishly -- that memory isn't the issue here.  There's plenty of slack after update does its thing.

I've had the display for a couple of days.  It came from Amazon. 

Given the LUTs are present in the other Waveshare-provided demos, I was expecting to see them for the 4.2" b/w/r in their demo code, but they're not there.  Guess they only publish them if there are changes from the default?

Doesn't look like the code in this PR is changing the LUTs, so I assume it's using the same waveforms the Waveshare demo code (which works for me) does.  I'll poke at it and see if I can get it to work.

**Comment by jknipper** [comment]
@sidoh Your sketch is working on my ESP8266 (NodeMcu v0.9), i have a different wiring of the display:
```
GxIO_Class io(SPI, SS, D3, D4);
GxEPD_Class display(io);
```
Maybe have a look at `GxGDEW042Z15/GxGDEW042Z15.h` for `display()` pin default settings.

**Comment by sidoh** [comment]
Ah wow, that was silly of me.  That definitely fixes it.  Thanks very much!

I was assuming that the display constructor would re-use the pins from `io`.  Should've looked more carefully at the code.  Seems like ideally it would, right?

**Comment by ZinggJM** [comment]
I have added my own version to my GxEPD library, now that I have one of the 4.2" 3-color e-papers.

**Pull request closed without merging**
